version: '3'
services:
  app:
    container_name: app-server
    image: owncloud:fpm
    stdin_open: true
    tty: true
    restart: always
    expose:
      - '80'
      - '9000'
    networks:
      - onlyoffice
    links:
      - mariadb:mysql
      - redis:redis
    environment:
      - OWNCLOUD_DOMAIN=localhost
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=owncloud
      - OWNCLOUD_DB_USERNAME=owncloud
      - OWNCLOUD_DB_PASSWORD=owncloud
      - OWNCLOUD_DB_HOST=mysql
      - OWNCLOUD_ADMIN_USERNAME=admin
      - OWNCLOUD_ADMIN_PASSWORD=admin
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
    volumes:
      - app_data:/var/www/html
      - ./docker-persist/owncloud/config:/var/www/html/config
  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
      - ./docker-persist/mariadb/conf.d:/etc/mysql/conf.d
      - ./docker-persist/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: owncloud
      MYSQL_PASSWORD: owncloud
      MYSQL_DATABASE: owncloud
    expose:
      - '3306'
      - '5432'
    restart: always
  redis:
    container_name: redis
    image: redis:alpine
    environment:
      - REDIS_DATABASES=1
    volumes:
      - ./docker-persist/redis/data:/data
    restart: always
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    networks:
      - onlyoffice
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - onlyoffice
    volumes:
      - ./docker-persist/nginx/nginx.conf:/etc/nginx/nginx.conf
      - app_data:/var/www/html
      - ./docker-persist/nginx/certs:/etc/nginx/certs
networks:
  onlyoffice:
    driver: 'bridge'
volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
